-keep class * extends androidx.room.RoomDatabase { *; }
-keep @interface androidx.room.*
-keep class org.gallery.swiper.data.entity.** { *; }
-keep class org.gallery.swiper.data.model.** { *; }
-keepclassmembers enum org.gallery.swiper.data.model.Decision { *; }
-keep class coil.decode.VideoFrameDecoder { *; }
-keep class androidx.media3.exoplayer.** { *; }
-keep class androidx.media3.ui.PlayerView { *; }
